# Generated by Django 4.2.16 on 2024-12-03 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mobile_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be 12 digits.', regex='^[0-9]{12}$')])),
                ('national_id', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Nations ID must be 15 digits.', regex='^[0-9]{15}$')])),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Resturant'), (2, 'Customer')], null=True)),
                ('date_joind', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modifiy_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
