# Generated by Django 4.2.16 on 2024-12-03 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Nations ID must be 15 digits.', regex='^[0-9]{15}$')]),
        ),
    ]
