# Generated by Django 4.2.16 on 2024-12-03 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits.', regex='^[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Nations ID must be 14 digits.', regex='^[0-9]{14}$')]),
        ),
    ]
