# Generated by Django 4.2.16 on 2024-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
